import argparse

parser = argparse.ArgumentParser(description='WOAD')
parser.add_argument('--lr', type=float, default=0.0001,help='learning rate (default: 0.0001)')
parser.add_argument('--batch-size', type=int, default=10, help='number of instances in a batch of data (default: 10)')
parser.add_argument('--model-name', default='final', help='name to save model')
parser.add_argument('--pretrained-ckpt', default=None, help='ckpt for pretrained model')
parser.add_argument('--feature-size', default=2048, help='size of feature (default: 2048)')
parser.add_argument('--num-class', type=int, default=20, help='number of classes (default: )')
parser.add_argument('--max-seqlen', type=int, default=750, help='maximum sequence length during training (default: 750)')
parser.add_argument('--Lambda', type=float, default=0.5, help='weight on TPG Loss (default: 0.5)')
parser.add_argument('--num-similar', default=3, help='number of similar pairs in a batch of data  (default: 3)')
parser.add_argument('--seed', type=int, default=1, help='random seed (default: 1)')
parser.add_argument('--max-iter', type=int, default=4000, help='maximum iteration to train (default: 4000)')
parser.add_argument('--warm_start', type=int, default=0)
parser.add_argument('--eval_intern', type=int, default=100)
parser.add_argument('--fps', type=float, default=1.5625)
parser.add_argument('--supervision', default='video', type=str, help='supervision type, video or segment')
parser.add_argument('--confidence_thred', type=float, default=0.7)
parser.add_argument('--hidden_size', type=int, default=4096)
parser.add_argument('--enc_steps', type=int, default=64)
parser.add_argument('--temp_window', type=int, default=4)
parser.add_argument('--sup_percent', type=float, default=1.0, help='percentage of gt labels used for training')
parser.add_argument('--mix_percent', type=float, default=0.9)
parser.add_argument('--weight_decay', type=float, default=0.0005)
